name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure this matches the version detected by Azure

      - name: Install Dependencies
        run: npm install --legacy-peer-deps # Use this flag to bypass peer dependency checks
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Replace with the root of your React project
          api_location: "" # Leave empty if no API
          output_location: "build" # This should match the build output directory
          app_build_command: "npm run build" # Explicitly specify the build command
          skip_app_build: false # Ensure the build step is not skipped

